$ANSIBLE_VAULT;1.1;AES256
62333932353830656665323232656264376235633435306130646237336135613466643539626430
6632633930383364383338386562363463346632353464360a646462363465373262313766316365
65626665383966346231626535653834323663666336396634313534663362396437313861363666
3933363030383361630a323534326263613032393962383334613830393635643662323365356532
64393539373465333064336433613639313630663864626430613237656462353765313264313461
31363262383436623362653033636436386131333463336361383461353631623663666564353562
39636365313662346239313334663933313030646434306132613633393738366139393564366662
31623833623062373766633962666234616666383538383434643339666533666634396437383232
63333637623235653030653832636161353039383739393038616631353337646134353530303034
31663963303932353864613466393937346163303763393937613330386237346135346138656264
30393966623862373130313534376565323030643538356566363539366234333332313139393631
62393463653862363137393835316431326264643434386366616338333162363933323039613934
32363236373762333038333037636138633761636239623161323565633738613137653233666436
62666231663263343965396239333765353438633231663031323939333864633736653437323662
32653339316661636465616262366261656230323931343830633330326338623061323238326630
37623766306631656663353662363939393432643166343332353237393165313537613630396634
65666363393139653362616130306236336130396631383061333137386262666135623036613132
39636162316363623635303139643730666364366638646338666663373434323338663462376138
36353066343832326365303865306664323866373038386264356636336264313830393831366531
33353136353862363466303732306635333035643863383737336639666265306661306462313539
65343138663333316530373561613038343039356334656233333562336466373137383361323539
36653561343961643838386631653435366234346564383132613132343663613264643762386635
39343137646138343132646562373634366136376566366630343139663462353133653436383032
37643863616339343339393331376336623534343239633432303064313333623864386466376332
37613564346136666633633936396239356332363466393933653532643134616234363436366165
3364633038373733316436613434313461333235346631663232
